config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  get 'progress_products/:job_id' => 'products#progress_job'
  get 'download_products' => 'products#download_csv', as: :download_csv
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
end

app/models/depot.rb
class Depot < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/depots_controller.rb
class DepotsController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @job = Delayed::Job.first
  end

  def download_csv
    @job = Delayed::Job.enqueue ProductJob.new(params[:depot_id], 'export_csv', 0)
  end

  def progress_job
    @job = Delayed::Job.where(id: params[:job_id]).first
    if @job.present?
       percentage = !@job.progress_max.zero? ? @job.progress_current / @job.progress_max.to_f * 100 : 0
       render json: @job.attributes.merge!(percentage: percentage).to_json
   	else
  		render json: ''
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/depots_helper.rb
module DepotsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DelayedJobWithPolling</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/products/download_csv.js.erb
progress_job('<%= @job.try(:id) %>');

app/views/products/index.html.erb
<div class="col-md-12">
  <br>
  <div class="export">
    <%= link_to 'Export Products', download_csv_path(depot_id: Depot.first.id), remote: true, class: 'btn btn-primary btn-lg' %>
    <div class="well">
      <div class="row">
        <div class="col-xs-12">
          <div class="progress-status text-primary">
            0/0
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <div class="`gress progress-striped active">
            <div class="progress-bar">
              <div class="text-primary">
                0%
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= link_to 'View csv', '/export.csv', class: 'btn btn-success export-link', style: 'display:none' %>
  </div>
</div>  

<script>
  $(document).ready(function(){
    progress_job('<%= @job.try(:id) %>');
  });
</script>